name: Build and Test

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build_and_test:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node 12.x
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Build
        run: npm run 
